### ISSUE TITLE
User实体里的updateFrom方法未给密码加密导致更新后以明文存储密码

### ISSUE THREAD

**Issue by Chennyh** [Snailclimb/spring-security-jwt-guide#19]
```java
    public void updateFrom(UserUpdateRequest userUpdateRequest) {
        if (Objects.nonNull(userUpdateRequest.getFullName())) {
            this.setFullName(userUpdateRequest.getFullName());
        }
        if (Objects.nonNull(userUpdateRequest.getPassword())) {
            this.setPassword(userUpdateRequest.getPassword());
        }
        if (Objects.nonNull(userUpdateRequest.getEnabled())) {
            this.setEnabled(userUpdateRequest.getEnabled());
        }
    }
```

**Comment by Snailclimb** [comment]
> ```java
>     public void updateFrom(UserUpdateRequest userUpdateRequest) {
>         if (Objects.nonNull(userUpdateRequest.getFullName())) {
>             this.setFullName(userUpdateRequest.getFullName());
>         }
>         if (Objects.nonNull(userUpdateRequest.getPassword())) {
>             this.setPassword(userUpdateRequest.getPassword());
>         }
>         if (Objects.nonNull(userUpdateRequest.getEnabled())) {
>             this.setEnabled(userUpdateRequest.getEnabled());
>         }
>     }
> ```

已经修改。
