### ISSUE TITLE
说明文档请修改一下

### ISSUE THREAD

**Issue by liufeiguo** [Snailclimb/spring-security-jwt-guide#20]
h2数据库页面访问地址 http://{host}:9333/h2-console/ 请修改为http://{host}:9333/api/h2-console/

**Comment by Snailclimb** [comment]
> h2数据库页面访问地址 http://{host}:9333/h2-console/ 请修改为http://{host}:9333/api/h2-console/

赞！

**Comment by Snailclimb** [comment]
> h2数据库页面访问地址 http://{host}:9333/h2-console/ 请修改为http://{host}:9333/api/h2-console/

已经修改。
![image](https://user-images.githubusercontent.com/29880145/89701230-5b9b8880-d967-11ea-8acf-8641ee0ce444.png)
