### ISSUE TITLE
前端访问产生cors问题

### ISSUE THREAD

**Issue by valeeraZ** [Snailclimb/spring-security-jwt-guide#21]
用postman测试一切正常，但是用axios访问就会有cors问题。
需要在`CorsConfiguration`里允许OPTION请求：
```java
.allowedMethods("GET", "POST", "DELETE", "PUT","OPTION")
```
详见[什么时候会发送OPTION请求](https://juejin.im/post/6844903821634699277)。

**Comment by Snailclimb** [comment]
> 用postman测试一切正常，但是用axios访问就会有cors问题。
> 需要在`CorsConfiguration`里允许OPTION请求：
> 
> ```java
> .allowedMethods("GET", "POST", "DELETE", "PUT","OPTION")
> ```
> 
> 详见[什么时候会发送OPTION请求](https://juejin.im/post/6844903821634699277)。

我记得我解决了这个问题 之前和前端联调过

**Comment by valeeraZ** [comment]
可能是因为我在请求头设置了Accept-Language，浏览器需要发送一个OPTION请求。
