### ISSUE TITLE
post调试工具

### ISSUE THREAD

**Issue by Xay20200415** [Snailclimb/spring-security-jwt-guide#36]
你好，Guide哥。看到你的调试工具很特别，不像postman。能问下你使用的是什么调试工具吗？
<img width="1064" alt="not-have-enough-permission" src="https://user-images.githubusercontent.com/63690490/171575952-f6121048-600e-4c87-9280-06d0958ede91.png">

**Comment by Snailclimb** [comment]
> 你好，Guide哥。看到你的调试工具很特别，不像postman。能问下你使用的是什么调试工具吗？ <img alt="not-have-enough-permission" width="1064" src="https://user-images.githubusercontent.com/63690490/171575952-f6121048-600e-4c87-9280-06d0958ede91.png">

https://insomnia.rest/ 这个工具哈。
